config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  resources :records do
    resources :reviews
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
  has_many :reviews

  validates :artist, :title, :price, :description, :genre, :album_length, presence: true
  validates :artist, :title, :genre, length: { in: 3..25 }
  validates :description, length: { maximum: 500 }

  scope :most_reviewed, -> {(
    select("records.id, records.artist, records.title, records.price, records.description, records.genre, records.album_length, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("records.id")
    .order("reviews_count DESC")
    .limit(5)
    )}

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :record

  validates :content, presence: true, length: { in: 3..250 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, :name, :sex, :dob, :email, presence: true

  has_attached_file :avatar, :styles => { :medium => "300x300#", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :is_admin?

  def is_admin?
    current_user && current_user.admin
  end

protected

  def configure_permitted_parameters
    added_attrs = [:avatar, :name, :sex, :dob, :admin, :username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @records = Record.most_reviewed
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action except: [:index, :show] do
    flash[:notice] = "Administrative credentials required" unless is_admin?
    redirect_to root_path unless is_admin?
  end

  def index
    @records = Record.all
  end

  def show
    @record = Record.find(params[:id])
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)
    if @record.save
    flash[:notice] = "Record successfully added!"
      redirect_to  record_path(@record)
    else
      render :new
    end
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])
    if @record.update(record_params)
      flash[:notice] = "Record successfully updated!"
      redirect_to record_path(@record)
    else
      render :edit
    end
  end

  def destroy
    @record = Record.find(params[:id])
    @record.reviews.each do |review|
      review.destroy
    end
    if @record.destroy
      flash[:notice] = "Record successfully removed!"
      redirect_to records_path
    end
  end

private
  def record_params
    params.require(:record).permit(:title, :artist, :price, :description, :album_length, :genre)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action do
    flash[:notice] = "Please login first" unless current_user
    redirect_to root_path unless current_user
  end

  before_action only: [:edit, :destroy] do
    review = Review.find(params[:id])
    flash[:notice] = "Unauthorised user" unless current_user.id === review.user.id || is_admin?
    redirect_to record_path(review.record) unless current_user.id === review.user.id || is_admin?
  end

  def new
    @record = Record.find(params[:record_id])
    @review = @record.reviews.new
  end

  def create
    @record = Record.find(params[:record_id])
    @review = @record.reviews.new(review_params)
    if @review.save
    flash[:notice] = "Review successfully added!"
      redirect_to  record_path(@record)
    else
      render :new
    end
  end

  def edit
    @record = Record.find(params[:record_id])
    @review = Review.find(params[:id])
  end

  def update
    @record = Record.find(params[:record_id])
    @review= Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review successfully updated!"
      redirect_to record_path(@record)
    else
      render :edit
    end
  end

  def destroy
    @record = Record.find(params[:record_id])
    @review = Review.find(params[:id])
    if @review.destroy
      flash[:notice] = "Review successfully removed!"
      redirect_to record_path(@record)
    end
  end

private
  def review_params
    params.require(:review).permit(:user_id, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KalamityRecords</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="my-nav">
      <div class="container">
        <div class="navbar-title"><%= link_to "Kalamity Records", root_path %></div>
        <div class="navbar-flash"><%= flash[:alert] %></div>
        <div class="navbar-flash"><%= flash[:notice] %></div>
        <div class="navbar-user"><%= ("Welcome " + current_user.username + "!") if current_user %></div>
        <div class="navbar-avatar"><%= image_tag(current_user.avatar.url(:thumb)) if current_user %></div>
        <div class="navbar-item"><%= link_to "Log Out", destroy_user_session_path, method: :delete if current_user %></div>
        <div class="navbar-item"><%= link_to "Settings", edit_user_registration_path if current_user %></div>
        <div class="navbar-item"><%= link_to "All Records", records_path %></div>
        <div class="navbar-item"><%= link_to "Add Records", new_record_path if current_user && current_user.admin === true %></div>
        <div class="navbar-item"><%= link_to "Login", new_user_session_path  if !current_user %></div>
        <div class="navbar-item"><%= link_to "Sign Up", new_user_registration_path if !current_user %></div>
      </div>
    </div>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h3><%= "Welcome to Kalamity Records" if !current_user %></h3>

<h4><%= "Kalamity Records is an online record store designed as a quick and easy way for visitors to checkout their favorite records. You can view all our records whether you have an account or not, but if you sign up you can leave reviews for others to see. The ability to shop is still under development, but check back soon and we'll have it up and running. If you don't have an account with us, sign up " if !current_user %><%= link_to "here", new_user_registration_path if !current_user %><%= " and get started." if !current_user %></h4>

<% if current_user %>

  <div id="home-title">Top Five Most Reviewed</div>

  <div class="home-records">
    <% @records.each do |record| %>
      <%= link_to record_path(record) do %>
        <div class="home-record">
          <h5><%= record.title %></h5>
          <%= record.artist %>
          <h6><%= record.genre %></h6>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/records/_form.html.erb
<%= render "layouts/errors", :object => @record %>

<%= form_for @record do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br><br>
  <%= f.label :artist %><br>
  <%= f.text_field :artist %><br><br>
  <%= f.label :price %><br>
  $<%= f.number_field :price %>.00<br><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br><br>
  <%= f.label :genre %><br>
  <%= f.text_field :genre %><br><br>
  <%= f.label :album_length %><br>
  <%= f.number_field :album_length %> minutes
  <br><br>
  <%= f.submit class: "new"  %>
  <%= link_to "Back", :back %>
<% end %>

app/views/records/edit.html.erb
<h1>Edit Record</h1>

<%= render "form" %>

app/views/records/index.html.erb
<div class="records">
  <% @records.each do |record| %>
    <%= link_to record_path(record) do %>
      <div class="record">
        <h4><%= record.title %></h4>
        <small>$<%= record.price %>.00</small>
        <h5><%= record.artist %></h5>
        <em><h6><%= record.genre %></h6></em>
      </div>
    <% end %>
  <% end %>
</div>

app/views/records/show.html.erb
<% if current_user && current_user.admin %>
  <span class="edit-btn"><%= link_to "Edit Record", edit_record_path(@record) %></span>
<% end %>
<% if current_user && current_user.admin %>
<span class="delete-btn"><%= link_to "Delete Record", record_path(@record),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></span>
<% end %>
<h1><%= @record.title %> <small>$<%= @record.price %>.00</small></h1>
<h2>Artist(s): <%= @record.artist %></h2>
<h3>Genre: <%= @record.genre %></h3>
<h4><%= @record.description %></h4>
<small><%= @record.album_length %> minutes</small>
<br>
<hr>

<div class="review-title">
  <h4>Reviews</h4>
  <% if current_user %>
    <span class="button"><%= link_to "Add Review", new_record_review_path(@record) %></span>
  <% end %>
</div>
<% if @record.reviews.any? %>
  <div class="reviews">
    <% @record.reviews.each do |review|  %>
      <div class="review">
        <span class="rating"><%= review.rating %>/5</span>
        <br>
        <%= review.content %>
        <br>
        by <%= review.user.username %>
        <span class="edit-review"><%= link_to "Edit Review", edit_record_review_path(@record, review) if current_user && (current_user.username === review.user.username || current_user.admin) %></span>
      </div>
    <% end %>
  </div>
<% else %>
  <p>There are no reviews for this product yet</p>
<% end %>
<br>
<span class="button"><%= link_to "Back", :back %></span>
<br>
<br>

app/views/reviews/_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@record, @review] do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.label :content %><br>
  <%= f.text_area :content %><br><br>
  <%= f.label :rating %><br>
  <%= f.select :rating, options_for_select([
    ["1", 1],
    ["2", 2],
    ["3", 3],
    ["4", 4],
    ["5", 5]
    ]), {}, {class: "form-control"} %>
    <br>
    <br>
    <%= f.submit class: "new"  %>
    <%= link_to "Back to Record", record_path(@record), class: "go-back" %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render "form" %>

<%= link_to "Delete Review", record_review_path(@record, @review),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render "form" %>